// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ug9aUQE0EjPkX6sHh8EaTeL9ExLepG0',
    appId: '1:236894866178:web:ee37cdde1062cb20b7101b',
    messagingSenderId: '236894866178',
    projectId: 'bodobox-server',
    authDomain: 'bodobox-server.firebaseapp.com',
    storageBucket: 'bodobox-server.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSTQ705fmZOkRcSWgcMYoMl7_HLadrs-A',
    appId: '1:236894866178:android:1e89355d91ae8e38b7101b',
    messagingSenderId: '236894866178',
    projectId: 'bodobox-server',
    storageBucket: 'bodobox-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPu88ZA-RCjwMLQtnOQysozyeKykZZdA',
    appId: '1:236894866178:ios:cdfd4e78fc5eaee9b7101b',
    messagingSenderId: '236894866178',
    projectId: 'bodobox-server',
    storageBucket: 'bodobox-server.appspot.com',
    iosBundleId: 'com.example.bodobox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByPu88ZA-RCjwMLQtnOQysozyeKykZZdA',
    appId: '1:236894866178:ios:eb1fdad7c1febf7fb7101b',
    messagingSenderId: '236894866178',
    projectId: 'bodobox-server',
    storageBucket: 'bodobox-server.appspot.com',
    iosBundleId: 'com.example.bodobox.RunnerTests',
  );
}
